### ISSUE TITLE
Problems with Voicevox

### ISSUE THREAD

**Issue by Li-amK** [SociallyIneptWeeb/LanguageLeapAI#35]
Soooooooo here i am opening an Issue because i've spent about two hours trying to fix it by myself and i'm tired of it now. Hopefully somebody can help.

I initially ran everything in google Collab and was constantly getting time-outs from my voicevox collab instance. I tested the translation in the `asr.py` file ans DeepL and whisper a playing niceley and that works just fine.
I get a translation of what i said printed in the terminal, and then the the problems start.
My Voicevox doesn't print anything to the collab console and won't react in the test in `voicevox.py` nor when i try to actually use it in the `voice_translator.py`.

The next thing i did is try to run just Voicevox it locally because maybe collab was playing up. I quickly noticed that i doesn't work with amd gpus so i pulled the cpu image from docker hub and ran it manually 
1) `docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest`
2) `docker run --rm -it -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest`

And now some things were happening (i was getting outputs from voicevox, yay!) but other still weren't.
Now everytime i say something i get following erros from the Console in which Voicevox is running:
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
reading /tmp/tmp5wmph5yu ... 57
emitting double-array: 100% |###########################################|

done!
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:50021 (Press CTRL+C to quit)
INFO:     172.17.0.1:48314 - "POST //audio_query?text=%E3%82%80%E3%81%8B%E3%81%97%E3%81%82%E3%82%8B%E3%81%A8%E3%81%93%E3%82%8D%E3%81%AB%E3%80%81%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF%E3%81%A8%E3%81%84%E3%81%86%E7%94%B7%E3%81%AE%E5%AD%
90%E3%81%8C%E3%81%84%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF%E3%81%AF%E3%81%8A%E6%AF%8D%E3%81%95%E3%82%93%E3%81%A8%E4%B8%80%E7%B7%92%E3%81%AB%E4%BD%8F%E3%82%93%E3%81%A7%E3%81%84%E3%81%BE%E3%81%97%E3%8
1%9F%E3%80%82&speaker=15 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:48316 - "POST //synthesis?speaker=15 HTTP/1.1" 404 Not Found
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
```
and these form the `voicevox.py` file:
```
Voicevox attempting to speak now...
Exception in thread Thread-1 (play_voice):
Exception in thread Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Thread-2 (play_voice):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\*\LanguageLeapAI-main\src\modules\voicevox.py", line 29, in play_voice
    self._target(*self._args, **self._kwargs)
  File "C:\*\LanguageLeapAI-main\src\modules\voicevox.py", line 29, in play_voice
    data, fs = sf.read(VOICEVOX_WAV_PATH, dtype='float32')
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 285, in read
    data, fs = sf.read(VOICEVOX_WAV_PATH, dtype='float32')
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 285, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 658, in __init__
    with SoundFile(file, 'r', samplerate, channels,
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 1216, in _open
    self._file = self._open(file, mode_int, closefd)
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\*\\LanguageLeapAI-main\\src\\audio\\voicevox.wav': Format not recognised.
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\*\\LanguageLeapAI-main\\src\\audio\\voicevox.wav': Format not recognised.

Process finished with exit code 0
```
as well as these from the `voice_translator.py`: (as you can see, the translation part works)

```
English: This is a test sentence.
Japanese: これはテスト文です。
Exception in thread Exception in thread Thread-4 (play_voice):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Thread-3 (play_voice):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run

  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\*\LanguageLeapAI-main\src\modules\voicevox.py", line 29, in play_voice
    self._target(*self._args, **self._kwargs)
  File "C:\*\LanguageLeapAI-main\src\modules\voicevox.py", line 29, in play_voice
    data, fs = sf.read(VOICEVOX_WAV_PATH, dtype='float32')
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 285, in read
    data, fs = sf.read(VOICEVOX_WAV_PATH, dtype='float32')
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 285, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 658, in __init__
    with SoundFile(file, 'r', samplerate, channels,
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 1216, in _open
    self._file = self._open(file, mode_int, closefd)
  File "C:\*\LanguageLeapAI-main\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\*\\LanguageLeapAI-main\\src\\audio\\voicevox.wav': Format not recognised.
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\*\\LanguageLeapAI-main\\src\\audio\\voicevox.wav': Format not recognised.
Closing voice translator.

Process finished with exit code 0
```

So yeah, that's about what i've done so far.

Help would be most appreciated!

**Comment by SociallyIneptWeeb** [comment]
I recently updated the voicevox Colab file, so maybe reupload the updated one and try running that instead. From the logs it looks like the voicevox docker using CPU is unable to generate a proper response

**Comment by Li-amK** [comment]
Thanks!
