### ISSUE TITLE
How to use whisper and voice translator together on Colab ?

### ISSUE THREAD

**Issue by SorenKyojin** [SociallyIneptWeeb/LanguageLeapAI#41]
I can't use them both, Google want to subscribe to Colab Pro

How can I use them both at the same time ?
Or it's not necessary ?

**Comment by BLINK-SG** [comment]
Use 2 different google accounts that should solve the problem.

**Comment by SorenKyojin** [comment]
Oh my god for the moment, everything is fine, NO ERROR !

(So I hope it will work)

**Comment by SorenKyojin** [comment]
I have a problem, it could be caused by Voicevox
The translator can't play the TTS:
```
Exception in thread Thread-4 (play_voice):
Traceback (most recent call last):
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "F:\LanguageLeapAI-main\src\modules\voicevox.py", line 30, in play_voice
    sd.play(data, fs, device=device_id)
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\sounddevice.py", line 175, in play
    ctx.start_stream(OutputStream, samplerate, ctx.output_channels,
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\sounddevice.py", line 2582, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\sounddevice.py", line 1494, in __init__
    _StreamBase.__init__(self, kind='output', wrap_callback='array',
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "C:\Users\Soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\sounddevice.py", line 2745, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening OutputStream: Unanticipated host error [PaErrorCode -9999]: 'Failed to load ASIO driver' [ASIO error 0]
```

**Comment by SociallyIneptWeeb** [comment]
This usually means it can't reach the cable output Audio Device to output the tts voice. Ensure that you have properly installed vac cable. And also check whether the audio device id for the cable output is set properly in the .env file

**Comment by SorenKyojin** [comment]
Okay, I'll do it tomorrow (french time lol)

**Comment by SorenKyojin** [comment]
So, I tried any audio device, it's the same error.
I think it's because Voicevox can't find the ASIO driver.
How can I make it load ?
